POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
    "title": "REST client is a handy tool", 
    "author": "Mr Great Mluukkai", 
    "url": "https://www.greatmluukkai.com", 
    "likes": 1000
}